image: node:16.13.0

pipelines:
  pull-requests:
    '**':
      - step:
          name: 'Publish to Chromatic'
          caches:
            - node
          script:
            - npm install
            - git checkout $BITBUCKET_BRANCH
            - npm run build:chromatic
            - npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN -d storybook-static --allow-console-errors --exit-zero-on-changes