name: Node.js Package

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish-gpr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: "Version and publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm install
          npm run build:monorepo
          npx lerna version --conventional-commits --conventional-graduate --yes
          npx lerna publish from-git --yes