name: Publish to NPM
on: [workflow_dispatch]
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Use NodeJS 16"
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: "Version and publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm install
          npx lerna bootstrap
          npm run build:monorepo
          npx lerna version --conventional-commits --yes
          npx lerna publish from-git --yes