name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_PACKAGES}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: echo "@canciolt:registry=https://npm.pkg.github.com/:_authToken=${{ secrets.PUBLISH_PACKAGES }}" > ~/.npmrc
      - run: npm publish